name: 1-actions-ci-cd-aks

on:
  push:
    branches: [ master ]
    paths: .github/workflows/1-actions-ci-cd-aks.yml
  pull_request:
    branches: none # [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy-aks:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: machripe
      IMAGE_NAME: node-web-app
      IMAGE_TAG: latest
    
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Build Docker Image
      run:
        docker build ./node-web-app/ --file ./node-web-app/Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
    - name: Login to Docker Hub
      run:
        echo "${{ secrets.DOCKER_REPOSITORY_PASSWORD }}" | docker login -u $DOCKER_REPOSITORY --password-stdin
    - name: Push Image to Docker Hub
      run:
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME/$IMAGE_TAG
